name: graphics
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  lottie: ^2.4.0
  flutter_svg: ^2.0.7
  image_picker: ^0.8.4
  services:
    path: ../services
  domain:
    path: ../domain



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  assets:
    - assets/pngs/
    - assets/svg/
    - assets/lotties/
