name: base_flutter_2026
description: A base flutter app structure with reactiv and clean
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^8.0.5
  reactiv: ^1.1.1
  image_capture_field: ^0.3.0
  flutter_svg: ^2.0.7
  file_picker: ^10.1.7
  lottie: ^2.4.0
  domain:
    path: packages/domain
  services:
    path: packages/services
  graphics:
    path: packages/graphics



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true